import { Column } from 'react-table';
import { Columns } from '@/types';
import { DESCRIPTIONANDUNITOFVARIABLES } from '.';

export const CONSENTTABLECOLUMNS: Column<Columns>[] = [
  {
    Header: 'Personal Data and Webcam',
    accessor: 'PDataAndWeb' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'Definition',
    accessor: 'Definition' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'List Of Unit',
    accessor: 'Unit' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'Companies',
    accessor: 'Companies' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'Use',
    accessor: 'Use' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'Price Offering',
    accessor: 'Pricing' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'Threshold',
    accessor: 'Threshold' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'Consent',
    accessor: 'Consent' as keyof Columns, // accessor is the "key" in the data
  },
  {
    Header: 'id',
    accessor: 'id' as keyof Columns, // accessor is the "key" in the data
  },
];
export const CONSENTTABLEDATA = {
  'EMOTIONAL OVERALL': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.emotional_overall.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.emotional_overall.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  WEATHER: {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.weather.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.weather.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'RELATIVE FINANCE STATUS': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.relative_finance_status.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.relative_finance_status.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'EXERCISE TIME': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.exercise_time.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.exercise_time.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'ANY SOCIAL LIFE': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.any_social_life.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.any_social_life.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'SOCIAL LIFE LIST': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.social_life_list.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.social_life_list.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'HEALTH OVERALL': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.health_overall.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.health_overall.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  WEIGHT: {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.weight.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.weight.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'FAMILY STATUS': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.family_status.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.family_status.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'DEVICE SCREEN TIME': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.device_screen_time.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.device_screen_time.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'WORK LIFE BALANCE': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.work_life_balance.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.work_life_balance.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  JOURNALING: {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.journaling.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.journaling.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  DATE: {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.date.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.date.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'EMOTIONAL LIST': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.emotional_list.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.emotional_list.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'HIGH TEMPERATURE': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.high_temperature.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.high_temperature.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  Photos: {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.photos.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.photos.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'LOW TEMPERATURE': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.low_temperature.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.low_temperature.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'Screen Recording': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.screen_recording.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.screen_recording.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'Camera Recording': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.camera_recording.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.camera_recording.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'Screen + Camera Recording': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.screen_camera_recording.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.screen_camera_recording.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'Microphone Audio Recording': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.microphone_audio_recording.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.microphone_audio_recording.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'System Audio Recording': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.system_audio_recording.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.system_audio_recording.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
  'Mic + System Recording': {
    Consent: 'FALSE',
    Definition: DESCRIPTIONANDUNITOFVARIABLES.mic_system_recording.definition,
    Unit: DESCRIPTIONANDUNITOFVARIABLES.mic_system_recording.unit,
    Companies: [],
    Use: '',
    Threshold: '',
    Pricing: '',
    id: null,
  },
};
