export enum DATATIMETYPE {
  DAY = '1 DAY',
  HOUR = '15 Mins',
  HALFMINS = '45 MINS',
  HOUR2 = '5 HOUR',
}
export const DATATIMETYPESOPTIONS = [
  { label: DATATIMETYPE.DAY, value: DATATIMETYPE.DAY },
  { label: DATATIMETYPE.HOUR, value: DATATIMETYPE.HOUR },
  { label: DATATIMETYPE.HALFMINS, value: DATATIMETYPE.HALFMINS },
  { label: DATATIMETYPE.HOUR2, value: DATATIMETYPE.HOUR2 },
];
